require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
    - "bin/*"
    - "db/migrate/*"
    - db/schema.rb
    - "docs/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"

Metrics/MethodLength:
  Max: 12
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Naming/VariableNumber:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Exclude:
    - "db/migrate/**"

Rails/RefuteMethods:
  Enabled: false

Rails/Validation:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true
